#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v25
# autospec commit: 9594167
#
Name     : ipp-crypto
Version  : 1.1.0
Release  : 24
URL      : https://github.com/intel/cryptography-primitives/archive/refs/tags/v1.1.0.tar.gz
Source0  : https://github.com/intel/cryptography-primitives/archive/refs/tags/v1.1.0.tar.gz
Summary  : Secure, fast and lightweight library of building blocks for cryptography, highly-optimized for various Intel® CPUs.
Group    : Development/Tools
License  : Apache-2.0
Requires: ipp-crypto-lib = %{version}-%{release}
Requires: ipp-crypto-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : nasm
BuildRequires : openssl-dev
BuildRequires : python3
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# Intel(R) Cryptography Primitives Library FIPS
## What is FIPS 140?
FIPS (Federal Information Processing Standard) 140 series are U.S. government
computer security standards that specify requirements for cryptography modules.
The latest version is FIPS 140-3 (ISO standard 19790).

%package dev
Summary: dev components for the ipp-crypto package.
Group: Development
Requires: ipp-crypto-lib = %{version}-%{release}
Provides: ipp-crypto-devel = %{version}-%{release}
Requires: ipp-crypto = %{version}-%{release}

%description dev
dev components for the ipp-crypto package.


%package dev32
Summary: dev32 components for the ipp-crypto package.
Group: Default
Requires: ipp-crypto-dev = %{version}-%{release}

%description dev32
dev32 components for the ipp-crypto package.


%package lib
Summary: lib components for the ipp-crypto package.
Group: Libraries
Requires: ipp-crypto-license = %{version}-%{release}

%description lib
lib components for the ipp-crypto package.


%package license
Summary: license components for the ipp-crypto package.
Group: Default

%description license
license components for the ipp-crypto package.


%prep
%setup -q -n cryptography-primitives-1.1.0
cd %{_builddir}/cryptography-primitives-1.1.0
pushd ..
cp -a cryptography-primitives-1.1.0 buildavx2
popd
pushd ..
cp -a cryptography-primitives-1.1.0 buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1745331496
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake .. -DARCH=intel64 \
-DCMAKE_INSTALL_PREFIX=/usr  -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
pushd ../buildavx2/
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
%cmake .. -DARCH=intel64 \
-DCMAKE_INSTALL_PREFIX=/usr  -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
popd
pushd ../buildavx512/
mkdir -p clr-build-avx512
pushd clr-build-avx512
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
GOAMD64=v4
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -Wl,-z,x86-64-v4 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -Wl,-z,x86-64-v4 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -Wl,-z,x86-64-v4 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v4 -mprefer-vector-width=512 "
%cmake .. -DARCH=intel64 \
-DCMAKE_INSTALL_PREFIX=/usr  -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
popd

%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1745331496
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/ipp-crypto
cp %{_builddir}/cryptography-primitives-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/ipp-crypto/ef9e55cdea6feb1b3b814480dabb2fe60ff2d738 || :
export GOAMD64=v2
pushd ../buildavx2/
GOAMD64=v3
pushd clr-build-avx2
%make_install_v3  || :
popd
popd
pushd ../buildavx512/
GOAMD64=v4
pushd clr-build-avx512
%make_install_v4  || :
popd
popd
GOAMD64=v2
pushd clr-build
%make_install
popd
## Remove excluded files
rm -f %{buildroot}*/usr/lib64/pkgconfig/ippcp-dynamic-ia32.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/ippcp-dynamic-intel64.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/ippcp-static-ia32-nonpic.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/ippcp-static-ia32.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/ippcp-static-intel64-nonpic.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/ippcp-static-intel64.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/crypto_mb-dynamic-intel64.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/crypto_mb-static-intel64.pc
## install_append content
mkdir -p %{buildroot}/usr/lib64
mkdir -p %{buildroot}-v3/usr/lib64
mkdir -p %{buildroot}-v4/usr/lib64
mv %{buildroot}/usr/lib/*/*so* %{buildroot}/usr/lib64
mv %{buildroot}-v3/usr/lib/*/*so* %{buildroot}-v3/usr/lib64
mv %{buildroot}-v4/usr/lib/*/*so* %{buildroot}-v4/usr/lib64
#rmdir %{buildroot}/usr/lib/*
## install_append end
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/tools/custom_library_tool_python/CLT_license_MIT.txt
/usr/tools/custom_library_tool_python/gui/app.py
/usr/tools/custom_library_tool_python/gui/controller.py
/usr/tools/custom_library_tool_python/gui/custom_functions_panel.py
/usr/tools/custom_library_tool_python/gui/selection_panel.py
/usr/tools/custom_library_tool_python/gui/settings_panel.py
/usr/tools/custom_library_tool_python/icon.ico
/usr/tools/custom_library_tool_python/main.py
/usr/tools/custom_library_tool_python/requirements.txt
/usr/tools/custom_library_tool_python/tests/functions_tests.py
/usr/tools/custom_library_tool_python/tests/utils.py
/usr/tools/custom_library_tool_python/tool/core.py
/usr/tools/custom_library_tool_python/tool/generators.py
/usr/tools/custom_library_tool_python/tool/generators_utils.py
/usr/tools/custom_library_tool_python/tool/package.py
/usr/tools/custom_library_tool_python/tool/utils.py
/usr/tools/intel64/staticlib/crypto_mb/ec_nistp256_k1.h
/usr/tools/intel64/staticlib/crypto_mb/ec_nistp256_l9.h
/usr/tools/intel64/staticlib/crypto_mb/ec_nistp384_k1.h
/usr/tools/intel64/staticlib/crypto_mb/ec_nistp384_l9.h
/usr/tools/intel64/staticlib/crypto_mb/ec_nistp521_k1.h
/usr/tools/intel64/staticlib/crypto_mb/ec_nistp521_l9.h
/usr/tools/intel64/staticlib/crypto_mb/ec_sm2_k1.h
/usr/tools/intel64/staticlib/crypto_mb/ec_sm2_l9.h
/usr/tools/intel64/staticlib/crypto_mb/ed25519_k1.h
/usr/tools/intel64/staticlib/crypto_mb/ed25519_l9.h
/usr/tools/intel64/staticlib/crypto_mb/exp_k1.h
/usr/tools/intel64/staticlib/crypto_mb/exp_l9.h
/usr/tools/intel64/staticlib/crypto_mb/rsa_k1.h
/usr/tools/intel64/staticlib/crypto_mb/rsa_l9.h
/usr/tools/intel64/staticlib/crypto_mb/sm3_k1.h
/usr/tools/intel64/staticlib/crypto_mb/sm3_l9.h
/usr/tools/intel64/staticlib/crypto_mb/sm4_ccm_k1.h
/usr/tools/intel64/staticlib/crypto_mb/sm4_ccm_l9.h
/usr/tools/intel64/staticlib/crypto_mb/sm4_gcm_k1.h
/usr/tools/intel64/staticlib/crypto_mb/sm4_gcm_l9.h
/usr/tools/intel64/staticlib/crypto_mb/sm4_k1.h
/usr/tools/intel64/staticlib/crypto_mb/sm4_l9.h
/usr/tools/intel64/staticlib/crypto_mb/version_k1.h
/usr/tools/intel64/staticlib/crypto_mb/version_l9.h
/usr/tools/intel64/staticlib/crypto_mb/x25519_k1.h
/usr/tools/intel64/staticlib/crypto_mb/x25519_l9.h
/usr/tools/intel64/staticlib/ippcp_e9.h
/usr/tools/intel64/staticlib/ippcp_g9.h
/usr/tools/intel64/staticlib/ippcp_h9.h
/usr/tools/intel64/staticlib/ippcp_k0.h
/usr/tools/intel64/staticlib/ippcp_k1.h
/usr/tools/intel64/staticlib/ippcp_l9.h
/usr/tools/intel64/staticlib/ippcp_m7.h
/usr/tools/intel64/staticlib/ippcp_n8.h
/usr/tools/intel64/staticlib/ippcp_p8.h
/usr/tools/intel64/staticlib/ippcp_s8.h
/usr/tools/intel64/staticlib/ippcp_w7.h
/usr/tools/intel64/staticlib/ippcp_y8.h

%files dev
%defattr(-,root,root,-)
/usr/include/crypto_mb/cpu_features.h
/usr/include/crypto_mb/defs.h
/usr/include/crypto_mb/ec_nistp256.h
/usr/include/crypto_mb/ec_nistp384.h
/usr/include/crypto_mb/ec_nistp521.h
/usr/include/crypto_mb/ec_sm2.h
/usr/include/crypto_mb/ed25519.h
/usr/include/crypto_mb/exp.h
/usr/include/crypto_mb/rsa.h
/usr/include/crypto_mb/sm3.h
/usr/include/crypto_mb/sm4.h
/usr/include/crypto_mb/sm4_ccm.h
/usr/include/crypto_mb/sm4_gcm.h
/usr/include/crypto_mb/status.h
/usr/include/crypto_mb/version.h
/usr/include/crypto_mb/x25519.h
/usr/include/ippcp.h
/usr/include/ippcpdefs.h
/usr/include/ippcpversion.h
/usr/include/ippversion.h
/usr/lib/cmake/ippcp/ippcp-config-version.cmake
/usr/lib/cmake/ippcp/ippcp-config.cmake

%files dev32
%defattr(-,root,root,-)
/usr/lib32/pkgconfig/ippcp-dynamic-ia32.pc
/usr/lib32/pkgconfig/ippcp-static-ia32-nonpic.pc
/usr/lib32/pkgconfig/ippcp-static-ia32.pc

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libcrypto_mb.so.12.1
/V3/usr/lib64/libippcp.so.12.1
/V4/usr/lib64/libcrypto_mb.so.12.1
/V4/usr/lib64/libippcp.so.12.1
/usr/lib64/libcrypto_mb.so
/usr/lib64/libcrypto_mb.so.12
/usr/lib64/libcrypto_mb.so.12.1
/usr/lib64/libippcp.so
/usr/lib64/libippcp.so.12
/usr/lib64/libippcp.so.12.1

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/ipp-crypto/ef9e55cdea6feb1b3b814480dabb2fe60ff2d738
