#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : ipp-crypto
Version  : ippcp.2021.6
Release  : 6
URL      : https://github.com/intel/ipp-crypto/archive/refs/tags/ippcp_2021.6.tar.gz
Source0  : https://github.com/intel/ipp-crypto/archive/refs/tags/ippcp_2021.6.tar.gz
Summary  : Secure, fast and lightweight library of building blocks for cryptography, highly-optimized for various Intel® CPUs.
Group    : Development/Tools
License  : Apache-2.0
Requires: ipp-crypto-lib = %{version}-%{release}
Requires: ipp-crypto-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : nasm
BuildRequires : openssl-dev
BuildRequires : python3

%description
# Intel® Integrated Performance Primitives Cryptography
[Build Instructions](./BUILD.md) | [Contributing Guide](#how-to-contribute) | [Documentation](#documentation) | [Get Help](#get-help) | [Intel IPP Product Page](https://software.intel.com/en-us/intel-ipp)

%package dev
Summary: dev components for the ipp-crypto package.
Group: Development
Requires: ipp-crypto-lib = %{version}-%{release}
Provides: ipp-crypto-devel = %{version}-%{release}
Requires: ipp-crypto = %{version}-%{release}

%description dev
dev components for the ipp-crypto package.


%package lib
Summary: lib components for the ipp-crypto package.
Group: Libraries
Requires: ipp-crypto-license = %{version}-%{release}

%description lib
lib components for the ipp-crypto package.


%package license
Summary: license components for the ipp-crypto package.
Group: Default

%description license
license components for the ipp-crypto package.


%prep
%setup -q -n ipp-crypto-ippcp_2021.6
cd %{_builddir}/ipp-crypto-ippcp_2021.6

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1662669948
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%cmake .. -DARCH=intel64 \
-DCMAKE_INSTALL_PREFIX=/usr
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1662669948
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/ipp-crypto
cp %{_builddir}/ipp-crypto-ippcp_2021.6/LICENSE %{buildroot}/usr/share/package-licenses/ipp-crypto/30001d543aa58e285d1984caabdd4631f2be514c || :
pushd clr-build
%make_install
popd
## install_append content
mkdir -p %{buildroot}/usr/lib64
mv %{buildroot}/usr/lib/*/*so* %{buildroot}/usr/lib64
#rmdir %{buildroot}/usr/lib/*
## install_append end

%files
%defattr(-,root,root,-)
/usr/tools/custom_library_tool_python/gui/app.py
/usr/tools/custom_library_tool_python/gui/controller.py
/usr/tools/custom_library_tool_python/gui/custom_functions_panel.py
/usr/tools/custom_library_tool_python/gui/selection_panel.py
/usr/tools/custom_library_tool_python/gui/settings_panel.py
/usr/tools/custom_library_tool_python/main.py
/usr/tools/custom_library_tool_python/tests/functions_tests.py
/usr/tools/custom_library_tool_python/tests/utils.py
/usr/tools/custom_library_tool_python/tool/core.py
/usr/tools/custom_library_tool_python/tool/generators.py
/usr/tools/custom_library_tool_python/tool/generators_utils.py
/usr/tools/custom_library_tool_python/tool/package.py
/usr/tools/custom_library_tool_python/tool/utils.py
/usr/tools/intel64/staticlib/ippcp_e9.h
/usr/tools/intel64/staticlib/ippcp_g9.h
/usr/tools/intel64/staticlib/ippcp_h9.h
/usr/tools/intel64/staticlib/ippcp_k0.h
/usr/tools/intel64/staticlib/ippcp_k1.h
/usr/tools/intel64/staticlib/ippcp_l9.h
/usr/tools/intel64/staticlib/ippcp_m7.h
/usr/tools/intel64/staticlib/ippcp_n0.h
/usr/tools/intel64/staticlib/ippcp_n8.h
/usr/tools/intel64/staticlib/ippcp_p8.h
/usr/tools/intel64/staticlib/ippcp_s8.h
/usr/tools/intel64/staticlib/ippcp_w7.h
/usr/tools/intel64/staticlib/ippcp_y8.h

%files dev
%defattr(-,root,root,-)
/usr/include/crypto_mb/cpu_features.h
/usr/include/crypto_mb/defs.h
/usr/include/crypto_mb/ec_nistp256.h
/usr/include/crypto_mb/ec_nistp384.h
/usr/include/crypto_mb/ec_nistp521.h
/usr/include/crypto_mb/ec_sm2.h
/usr/include/crypto_mb/ed25519.h
/usr/include/crypto_mb/exp.h
/usr/include/crypto_mb/rsa.h
/usr/include/crypto_mb/sm3.h
/usr/include/crypto_mb/sm4.h
/usr/include/crypto_mb/status.h
/usr/include/crypto_mb/version.h
/usr/include/crypto_mb/x25519.h
/usr/include/ippcp.h
/usr/include/ippcpdefs.h
/usr/include/ippversion.h
/usr/lib/cmake/ippcp/ippcp-config-version.cmake
/usr/lib/cmake/ippcp/ippcp-config.cmake
/usr/lib64/pkgconfig/crypto_mb-dynamic-intel64.pc
/usr/lib64/pkgconfig/crypto_mb-static-intel64.pc
/usr/lib64/pkgconfig/ippcp-dynamic-ia32.pc
/usr/lib64/pkgconfig/ippcp-dynamic-intel64.pc
/usr/lib64/pkgconfig/ippcp-static-ia32-nonpic.pc
/usr/lib64/pkgconfig/ippcp-static-ia32.pc
/usr/lib64/pkgconfig/ippcp-static-intel64-nonpic.pc
/usr/lib64/pkgconfig/ippcp-static-intel64.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libcrypto_mb.so
/usr/lib64/libcrypto_mb.so.11
/usr/lib64/libcrypto_mb.so.11.4
/usr/lib64/libippcp.so
/usr/lib64/libippcp.so.11
/usr/lib64/libippcp.so.11.4

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/ipp-crypto/30001d543aa58e285d1984caabdd4631f2be514c
