#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : ipp-crypto
Version  : ippcp.2020u3
Release  : 2
URL      : https://github.com/intel/ipp-crypto/archive/refs/tags/ippcp_2020u3.tar.gz
Source0  : https://github.com/intel/ipp-crypto/archive/refs/tags/ippcp_2020u3.tar.gz
Summary  : %{product_name}
Group    : Development/Tools
License  : Apache-2.0
Requires: ipp-crypto-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : nasm
BuildRequires : openssl-dev
BuildRequires : python3

%description
# Intel® Integrated Performance Primitives Cryptography
[Build Instructions](./BUILD.md) | [Contributing Guide](#how-to-contribute) | [Documentation](#documentation) | [Get Help](#get-help) | [Intel IPP Product Page](https://software.intel.com/en-us/intel-ipp)

%package dev
Summary: dev components for the ipp-crypto package.
Group: Development
Provides: ipp-crypto-devel = %{version}-%{release}
Requires: ipp-crypto = %{version}-%{release}

%description dev
dev components for the ipp-crypto package.


%package license
Summary: license components for the ipp-crypto package.
Group: Default

%description license
license components for the ipp-crypto package.


%prep
%setup -q -n ipp-crypto-ippcp_2020u3
cd %{_builddir}/ipp-crypto-ippcp_2020u3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1616776011
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%cmake .. -DARCH=intel64
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1616776011
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/ipp-crypto
cp %{_builddir}/ipp-crypto-ippcp_2020u3/LICENSE %{buildroot}/usr/share/package-licenses/ipp-crypto/9cff2ac4edb537b1ae09dc9dde0260cb28d00a9e
pushd clr-build
%make_install
popd
## install_append content
mkdir -p %{buildroot}/usrlib64
mv %{buildroot}/usr/lib/*/*so %{buildroot}/usr/lib64
rmdir %{buildroot}/usr/lib/*
## install_append end

%files
%defattr(-,root,root,-)
/usr/lib64
/usr/tools/custom_library_tool_python/gui/app.py
/usr/tools/custom_library_tool_python/gui/controller.py
/usr/tools/custom_library_tool_python/gui/custom_functions_panel.py
/usr/tools/custom_library_tool_python/gui/selection_panel.py
/usr/tools/custom_library_tool_python/gui/settings_panel.py
/usr/tools/custom_library_tool_python/icon.ico
/usr/tools/custom_library_tool_python/main.py
/usr/tools/custom_library_tool_python/tests/functions_tests.py
/usr/tools/custom_library_tool_python/tests/utils.py
/usr/tools/custom_library_tool_python/tool/core.py
/usr/tools/custom_library_tool_python/tool/generators.py
/usr/tools/custom_library_tool_python/tool/generators_utils.py
/usr/tools/custom_library_tool_python/tool/package.py
/usr/tools/custom_library_tool_python/tool/utils.py
/usr/tools/intel64/staticlib/ippcp_e9.h
/usr/tools/intel64/staticlib/ippcp_g9.h
/usr/tools/intel64/staticlib/ippcp_h9.h
/usr/tools/intel64/staticlib/ippcp_k0.h
/usr/tools/intel64/staticlib/ippcp_l9.h
/usr/tools/intel64/staticlib/ippcp_m7.h
/usr/tools/intel64/staticlib/ippcp_n0.h
/usr/tools/intel64/staticlib/ippcp_n8.h
/usr/tools/intel64/staticlib/ippcp_p8.h
/usr/tools/intel64/staticlib/ippcp_s8.h
/usr/tools/intel64/staticlib/ippcp_w7.h
/usr/tools/intel64/staticlib/ippcp_y8.h

%files dev
%defattr(-,root,root,-)
/usr/include/ippcp.h
/usr/include/ippcpdefs.h
/usr/include/ippversion.h

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/ipp-crypto/9cff2ac4edb537b1ae09dc9dde0260cb28d00a9e
